Repository OpenCodeFoundation/asset-manager, pull requests merged in 2018-06, with the labels that each got.

#77 Component Create
  src/AssetManager.Core/Entities/Components.cs
  src/AssetManager.Core/Entities/Location.cs
  src/AssetManager.Web/Controllers/ComponentsController.cs
  src/AssetManager.Web/Views/Components/Create.cshtml
  src/AssetManager.Web/Views/Locations/Create.cshtml
Labels: enhancement, review

#78 Software Licenses create user interface
  src/AssetManager.Core/Entities/License.cs
  src/AssetManager.Web/Controllers/LicensesController.cs
  src/AssetManager.Web/Views/Categories/Create.cshtml
  src/AssetManager.Web/Views/Companies/Create.cshtml
  src/AssetManager.Web/Views/Consumables/Create.cshtml
  src/AssetManager.Web/Views/Departments/Create.cshtml
  src/AssetManager.Web/Views/Depreciation/Create.cshtml
  src/AssetManager.Web/Views/Fields/Create.cshtml
  src/AssetManager.Web/Views/Licenses/Create.cshtml
  src/AssetManager.Web/Views/Locations/Create.cshtml
  src/AssetManager.Web/Views/Manufacturers/Create.cshtml
  src/AssetManager.Web/Views/Models/Create.cshtml
  src/AssetManager.Web/Views/StatusLabels/Create.cshtml
  src/AssetManager.Web/Views/Supplier/Create.cshtml
Labels: enhancement

#79 Create Accessory user interface
  src/AssetManager.Core/Entities/Accessory.cs
  src/AssetManager.Web/Controllers/AccessoriesController.cs
  src/AssetManager.Web/Views/Accessories/Create.cshtml
Labels: enhancement

#81 Status lablels header design change
  src/AssetManager.Web/Views/Shared/_Layout.cshtml
  src/AssetManager.Web/Views/StatusLabels/Index.cshtml
  src/AssetManager.Web/wwwroot/css/design.css
Labels: bug fixes

#82 Change header design StatusLabel Edit,details
  src/AssetManager.Web/Views/StatusLabels/Create.cshtml
  src/AssetManager.Web/Views/StatusLabels/Delete.cshtml
  src/AssetManager.Web/Views/StatusLabels/Details.cshtml
  src/AssetManager.Web/Views/StatusLabels/Edit.cshtml
Labels: bug fixes
