Repository OpenCodeFoundation/asset-manager, pull requests merged in 2018-05, with the labels that each got.

#32 Feature supplier
  src/AssetManager.Core/Entities/Supplier.cs
  src/AssetManager.Infrastructure/Data/AssetManagerContext.cs
  src/AssetManager.Infrastructure/Data/EfRepository.cs
  src/AssetManager.Web/Controllers/CompaniesController.cs
  src/AssetManager.Web/Controllers/SupplierController.cs
  src/AssetManager.Web/Views/Companies/Create.cshtml
  src/AssetManager.Web/Views/Companies/Delete.cshtml
  src/AssetManager.Web/Views/Companies/Details.cshtml
  src/AssetManager.Web/Views/Companies/Edit.cshtml
  src/AssetManager.Web/Views/Companies/Index.cshtml
  src/AssetManager.Web/Views/Shared/_Layout.cshtml
  src/AssetManager.Web/Views/Supplier/Create.cshtml
  src/AssetManager.Web/Views/Supplier/Delete.cshtml
  src/AssetManager.Web/Views/Supplier/Details.cshtml
  src/AssetManager.Web/Views/Supplier/Edit.cshtml
  src/AssetManager.Web/Views/Supplier/Index.cshtml
  src/AssetManager.Web/Views/_ViewImports.cshtml
Labels: fix

#36 Category
  src/AssetManager.Core/Entities/Category.cs
  src/AssetManager.Infrastructure/Data/AssetManagerContext.cs
  src/AssetManager.Web/Controllers/CategoriesController.cs
  src/AssetManager.Web/Views/Categories/Create.cshtml
  src/AssetManager.Web/Views/Categories/Delete.cshtml
  src/AssetManager.Web/Views/Categories/Details.cshtml
  src/AssetManager.Web/Views/Categories/Edit.cshtml
  src/AssetManager.Web/Views/Categories/Index.cshtml
Labels: enhancement

#40 Feature manufacturer
  src/AssetManager.Core/Entities/Manufacturer.cs
  src/AssetManager.Infrastructure/Data/AssetManagerContext.cs
  src/AssetManager.Web/Controllers/CompaniesController.cs
  src/AssetManager.Web/Controllers/ManufacturersController.cs
  src/AssetManager.Web/Views/Manufacturers/Create.cshtml
  src/AssetManager.Web/Views/Manufacturers/Delete.cshtml
  src/AssetManager.Web/Views/Manufacturers/Details.cshtml
  src/AssetManager.Web/Views/Manufacturers/Edit.cshtml
  src/AssetManager.Web/Views/Manufacturers/Index.cshtml
  src/AssetManager.Web/Views/Shared/_Layout.cshtml
Labels: enhancement

#44 Feature status label
  src/AssetManager.Core/Entities/StatusLabel.cs
  src/AssetManager.Infrastructure/Data/AssetManagerContext.cs
  src/AssetManager.Web/Controllers/CategoriesController.cs
  src/AssetManager.Web/Controllers/StatusLabelsController.cs
  src/AssetManager.Web/Views/Shared/_Layout.cshtml
  src/AssetManager.Web/Views/StatusLabels/Create.cshtml
  src/AssetManager.Web/Views/StatusLabels/Delete.cshtml
  src/AssetManager.Web/Views/StatusLabels/Details.cshtml
  src/AssetManager.Web/Views/StatusLabels/Edit.cshtml
  src/AssetManager.Web/Views/StatusLabels/Index.cshtml
Labels: enhancement

#46 Custom fields added
  src/AssetManager.Core/Entities/CustomFields.cs
  src/AssetManager.Infrastructure/Data/AssetManagerContext.cs
  src/AssetManager.Web/Controllers/FieldsController.cs
  src/AssetManager.Web/Views/Fields/Create.cshtml
  src/AssetManager.Web/Views/Fields/Delete.cshtml
  src/AssetManager.Web/Views/Fields/Index.cshtml
  src/AssetManager.Web/Views/Shared/_Layout.cshtml
Labels: enhancement

#47 Feature asset model
  src/AssetManager.Core/Entities/Asset.cs
  src/AssetManager.Core/Entities/Category.cs
  src/AssetManager.Core/Entities/Depreciation.cs
  src/AssetManager.Core/Entities/Manufacturer.cs
  src/AssetManager.Core/Entities/Models.cs
  src/AssetManager.Core/SharedKernel/Entity.cs
  src/AssetManager.Infrastructure/Class1.cs
  src/AssetManager.Infrastructure/Data/AssetManagerContext.cs
  src/AssetManager.Infrastructure/Data/EfRepository.cs
  src/AssetManager.Web/Controllers/CategoriesController.cs
  src/AssetManager.Web/Controllers/CompaniesController.cs
  src/AssetManager.Web/Controllers/DepreciationController.cs
  src/AssetManager.Web/Controllers/FieldsController.cs
  src/AssetManager.Web/Controllers/ManufacturersController.cs
  src/AssetManager.Web/Controllers/ModelsController.cs
  src/AssetManager.Web/Controllers/StatusLabelsController.cs
  src/AssetManager.Web/Controllers/SupplierController.cs
  src/AssetManager.Web/Views/Categories/Create.cshtml
  src/AssetManager.Web/Views/Companies/Create.cshtml
  src/AssetManager.Web/Views/Depreciation/Create.cshtml
  src/AssetManager.Web/Views/Fields/Create.cshtml
  src/AssetManager.Web/Views/Manufacturers/Create.cshtml
  src/AssetManager.Web/Views/Models/Create.cshtml
  src/AssetManager.Web/Views/Models/Delete.cshtml
  src/AssetManager.Web/Views/Models/Details.cshtml
  src/AssetManager.Web/Views/Models/Edit.cshtml
  src/AssetManager.Web/Views/Models/Index.cshtml
  src/AssetManager.Web/Views/Shared/_Layout.cshtml
  src/AssetManager.Web/Views/StatusLabels/Create.cshtml
  src/AssetManager.Web/Views/StatusLabels/Edit.cshtml
  src/AssetManager.Web/Views/Supplier/Create.cshtml
Labels: enhancement

#51 Feature locations
  src/AssetManager.Core/Entities/Location.cs
  src/AssetManager.Infrastructure/Data/AssetManagerContext.cs
  src/AssetManager.Web/Controllers/DepartmentsController.cs
  src/AssetManager.Web/Controllers/LocationsController.cs
  src/AssetManager.Web/Service/AllCountry.cs
  src/AssetManager.Web/Views/Locations/Create.cshtml
  src/AssetManager.Web/Views/Locations/Delete.cshtml
  src/AssetManager.Web/Views/Locations/Details.cshtml
  src/AssetManager.Web/Views/Locations/Edit.cshtml
  src/AssetManager.Web/Views/Locations/Index.cshtml
  src/AssetManager.Web/Views/Models/Create.cshtml
  src/AssetManager.Web/Views/Shared/_Layout.cshtml
Labels: enhancement

#52 Feature department
  src/AssetManager.Core/Entities/Company.cs
  src/AssetManager.Core/Entities/Departments.cs
  src/AssetManager.Core/Entities/Location.cs
  src/AssetManager.Infrastructure/Data/AssetManagerContext.cs
  src/AssetManager.Web/Controllers/CategoriesController.cs
  src/AssetManager.Web/Controllers/DepartmentsController.cs
  src/AssetManager.Web/Controllers/DepreciationController.cs
  src/AssetManager.Web/Controllers/FieldsController.cs
  src/AssetManager.Web/Controllers/LocationsController.cs
  src/AssetManager.Web/Controllers/ManufacturersController.cs
  src/AssetManager.Web/Controllers/ModelsController.cs
  src/AssetManager.Web/Controllers/StatusLabelsController.cs
  src/AssetManager.Web/Controllers/SupplierController.cs
  src/AssetManager.Web/Views/Departments/Create.cshtml
  src/AssetManager.Web/Views/Departments/Delete.cshtml
  src/AssetManager.Web/Views/Departments/Details.cshtml
  src/AssetManager.Web/Views/Departments/Edit.cshtml
  src/AssetManager.Web/Views/Departments/Index.cshtml
Labels: enhancement

#59 Hasrdware Controller added as a asset controller.
  src/AssetManager.Infrastructure/Data/AssetManagerContext.cs
  src/AssetManager.Web/Controllers/HardwareController.cs
  src/AssetManager.Web/Views/Hardware/Index.cshtml
  src/AssetManager.Web/Views/Shared/_Layout.cshtml
Labels: enhancement

#60 Component Controller added.
  src/AssetManager.Core/Entities/Components.cs
  src/AssetManager.Web/Controllers/ComponentsController.cs
  src/AssetManager.Web/Views/Components/Index.cshtml
Labels: enhancement

#62 Accessories controller added
  src/AssetManager.Infrastructure/Data/AssetManagerContext.cs
  src/AssetManager.Web/Controllers/AccessoriesController.cs
Labels: enhancement

#61 Consumables Controller added
  src/AssetManager.Web/Controllers/ConsumablesController.cs
Labels: enhancement

#63 Index user interface to show all accessories
  src/AssetManager.Core/Entities/Accessory.cs
  src/AssetManager.Web/Controllers/AccessoriesController.cs
  src/AssetManager.Web/Views/Accessories/Index.cshtml
  src/AssetManager.Web/Views/Shared/_Layout.cshtml
Labels: enhancement

#65 Licenses controller added with index user interface
  src/AssetManager.Core/Entities/License.cs
  src/AssetManager.Infrastructure/Data/AssetManagerContext.cs
  src/AssetManager.Web/Controllers/LicensesController.cs
  src/AssetManager.Web/Views/Licenses/Index.cshtml
  src/AssetManager.Web/Views/Shared/_Layout.cshtml
Labels: enhancement

#70 run bower install before running bundle
  src/AssetManager.Web/AssetManager.Web.csproj
Labels: bug fixes

#71 dropdown modified
  src/AssetManager.Core/Entities/Category.cs
  src/AssetManager.Core/Entities/Supplier.cs
  src/AssetManager.Web/Controllers/SupplierController.cs
  src/AssetManager.Web/Views/Categories/Create.cshtml
  src/AssetManager.Web/Views/Categories/Index.cshtml
  src/AssetManager.Web/Views/Consumables/Create.cshtml
  src/AssetManager.Web/Views/Departments/Create.cshtml
  src/AssetManager.Web/Views/Locations/Create.cshtml
  src/AssetManager.Web/Views/Models/Create.cshtml
  src/AssetManager.Web/Views/StatusLabels/Create.cshtml
  src/AssetManager.Web/Views/Supplier/Create.cshtml
Labels: fix

#73 use in-memory database for demo env
  src/AssetManager.Web/Startup.cs
Labels: bug fixes

#74 use external source for font-awesome
  src/AssetManager.Web/Views/Shared/_Layout.cshtml
  src/AssetManager.Web/bundleconfig.json
Labels: review

#75 copyright modified
  src/AssetManager.Web/Views/Shared/_Layout.cshtml
Labels: review

#76 Model Class Modified
  src/AssetManager.Core/Entities/Asset.cs
  src/AssetManager.Core/Entities/AssetLog.cs
  src/AssetManager.Core/Entities/AssetMaintenance.cs
  src/AssetManager.Core/Entities/CheckoutRequest.cs
  src/AssetManager.Core/Entities/ComponentsAssets.cs
  src/AssetManager.Core/Entities/LicenseSeat.cs
Labels: review
